ravitemer/mcphub.nvim

lua/mcphub/utils/installers.lua
fix: https://github.com/ravitemer/mcphub.nvim/issues/21
Dependencies: https://github.com/yetone/avante.nvim/pull/1603
=> fix: avante mcp server installer

lua/mcphub/ui/views/marketplace.lua
Add "Most Downloads" sort option to marketplace view to sort packages by their download count.
=> feat(ui): add downloads sorting option to marketplace

README.md, doc/mcphub.txt, lua/mcphub/ui/init.lua
Hello,
I would like to add the ability to configure window options (vim.wo) for the MCPHup window.
I'm currently using this to remove predefined window highlights and use winblend:
```lua
opts = {
ui = {
wo = {
winblend = vim.o.winblend,
winhl = '',
},
},
}
```
=> feat(ui): add configurable window options

lua/mcphub/utils/prompt.lua
These result true:
```
:=true or true
:=false or true
:=nil or true
```
=> fix: `add_example = add_example or true` always returns true

README.md
I was previously lost on how to use but it appears docs which explains #
and /mcp refers to things not available on any server I use.
What seems available everywhere and he's the most important, tools, does
not seems clearly mentionned so I made it clearer.
=> docs: explain codecompanion better

lua/mcphub/extensions/utils.lua, lua/mcphub/ui/capabilities/base.lua, lua/mcphub/utils/ui.lua
Before the prompt input only accepted a single line input. Enhance it to create a centered buffer that accepts multi-line input. I am new to Lua so please feel free to make any changes you want. I set the default key binding to be `<C-s>` to submit and `<C-q>` to quit out of the prompt input. Works with Avante and CodeCompanion.
=> Enhance MCP prompt params input window into multi-line

lua/mcphub/extensions/codecompanion.lua
Hi! 👋 
I started to get the following error when calling the `@mcp` tool on CodeCompanion:
```
E5108: Error executing lua: ...lazy/mcphub.nvim/lua/mcphub/extensions/codecompanion.lua:208: attempt to call method 'get_use_mcp_tool_prompt' (a nil value)
stack traceback:
...lazy/mcphub.nvim/lua/mcphub/extensions/codecompanion.lua:208: in function 'system_prompt'
...ompanion.nvim/lua/codecompanion/strategies/chat/init.lua:633: in function 'add_tool'
...n.nvim/lua/codecompanion/strategies/chat/agents/init.lua:280: in function 'parse'
...ompanion.nvim/lua/codecompanion/strategies/chat/init.lua:673: in function 'apply_tools_and_variables'
...ompanion.nvim/lua/codecompanion/strategies/chat/init.lua:728: in function 'submit'
...anion.nvim/lua/codecompanion/strategies/chat/keymaps.lua:216: in …
```
=> Fix system prompt from CodeCompanion extension

lua/mcphub/utils/highlights.lua
The current use of `nvim_set_hl` will override any MCPHub.nvim highlight groups that have been set by external sources such as themes or a user's config. This occurs when MCPHub.nvim is loaded first.
As per the vim docs:
```
nvim_set_hl({ns_id}, {name}, {val})                            *nvim_set_hl()*
Sets a highlight group.
Note: ~
• Unlike the `:highlight` command which can update a highlight group,
this function completely replaces the definition. For example:
`nvim_set_hl(0, 'Visual', {})` will clear the highlight group
'Visual'.
• The fg and bg keys also accept the string values `"fg"` or `"bg"`
which act as aliases to the corresponding foreground and background
values of the Normal group. If the Normal group has not been defined,
using these values results in an error.
• If `link` …
```
=> fix(highlights): don't override existing definitions

lua/mcphub/extensions/codecompanion/utils.lua
Feel free to discard this btw - I'm not precious and this is your wonderful piece of work.
I've styled all CodeCompanion's tools to use bolds for the tool name and then a brief description of the output, followed by the output itself. If we wrap the output in a codeblock then we can use `gy` to copy it.
Btw, I haven't tested this but just mocked up what the output should look like in CodeCompanion.
N/A
=> refactor: format output messages

lua/mcphub/ui/views/main.lua
replace confirm with select when delete server
This UI is with `snack.nvim`
=> feat: replace confirm with select when delete server

doc/mcphub.txt, lua/mcphub/utils/validation.lua
This pull request addresses two issues related to the handling and creation of the MCPHub configuration file (`mcphub.json`) within the `validate_config_file` function:
1.  **Automatic Directory Creation:** Previously, if the specified configuration file path included directories that didn't exist, attempting to create the default configuration file would fail. This change ensures that all necessary parent directories are created automatically before writing the default file, improving the setup experience for users who prefer custom configuration locations.
2.  **Correct Default JSON Structure:** The default configuration was incorrectly generating `{"mcpServers":[]}` (an empty array) instead of the expected `{"mcpServers":{}}` (an empty object). This has been fixed by using …
=> Small fixes to first time config creation

lua/mcphub/extensions/codecompanion/init.lua
This PR resolves a schema validation error related to the use_mcp_tool function definition used in the OpenAI API.
When strict: true is set, the schema requires the tool_input object to explicitly define all properties and set additionalProperties: false. However, our current design uses implicit input structures for tool_input, meaning the keys are not predefined. This leads to the following error:
```
[ERROR] 2025-05-11 01:58:22                                                                                                                                                 
Error: {                                                                                                                                                                    
"error": { …
```
=> Turn use_mcp_tool strict field to be false

lua/mcphub/extensions/codecompanion/utils.lua
Some popular MCP libraries will return an empty content block if the return value of a method is None or void.  This PR provides a simple response that respects the tool_call protocol's need to always respond to the LLM with some content.
=> support mcp tools that don't return content

.github/workflows/nix-build.yml, flake.nix
I added plenary as a dependency for the nix package. I also added a workflow to make sure that the nix package always works. This change was necessary because some modules didn't pass the check.
=> fix: add plenary as a dependency in nix flake

lua/mcphub/utils/prompt.lua
When an MCP server had only resource templates (and not any non-templated resources), the LLM wasn't being informed of the existence of the templated resources.
N/A
N/A
- [N/A] I've updated the README and/or relevant docs pages
- [N/A] I've run `make docs` to update the vimdoc pages
=> Fix bug when server has only resource templates

doc/mcphub.txt, lua/mcphub/init.lua, lua/mcphub/ui/views/base.lua, lua/mcphub/ui/views/main.lua, lua/mcphub/utils/validation.lua, plugin/mcphub.lua
Implements the ability to configure MCPHub without requiring a `setup()` call, addressing #166.
- **Auto-setup**: Plugin automatically initializes when `vim.g.mcphub` is set
- **On-demand UI**: `:MCPHub` command creates UI instance if needed
- **Decoupled initialization**: Command creation moved to `plugin/` directory
- **Enhanced welcome screen**: Shows configuration examples when not initialized
- **Full backward compatibility**: Existing `setup()` calls continue to work
```lua
-- Option 1: Global configuration (new, recommended)
vim.g.mcphub = { port = 37373, auto_approve = false }
-- Option 2: Traditional setup (still supported)
require("mcphub").setup({ port = 37373 })
-- Option 3: No config (show help info about setting up mcphub)
-- Just run :MCPHub
```
- ✅ Works with package …
=> feat: add vim.g.mcphub configuration support

lua/mcphub/extensions/codecompanion/init.lua
Change in commit 18710672477a3d9bb83ff1300bb934ef10127161 a couple of days ago breaks CodeCompanion help window (shown by `?` in chat window) - looks like group description must not be multi-line.
Right now pressing `?` result in this error:
```
E5108: Error executing lua: ...m/lazy/codecompanion.nvim/lua/codecompanion/utils/ui.lua:33: 'replace
ment string' item contains newlines                                                                 
stack traceback:                                                                                    
[C]: in function 'nvim_buf_set_lines'                                                       
...m/lazy/codecompanion.nvim/lua/codecompanion/utils/ui.lua:33: in function 'create_float'  
...anion.nvim/lua/codecompanion/strategies/chat/keymaps.lua:134: …
```
=> fix(codecompanion): help for @mcp in chat window

doc/installation.md, doc/mcphub.txt, lua/mcphub/hub.lua, lua/mcphub/ui/views/config.lua, lua/mcphub/utils/init.lua, lua/mcphub/utils/text.lua
Followup for https://github.com/ravitemer/mcphub.nvim/pull/199
This pull request introduces an enhancement to the pretty_json function in lua/mcphub/utils/init.lua, adding support for using the jq command-line tool for JSON formatting when available. If jq is not installed, the function falls back to the existing custom implementation.
Enhancements to JSON formatting:
[lua/mcphub/utils/init.lua](https://github.com/ravitemer/mcphub.nvim/pull/199/files#diff-2ae8864d8902fe0ae8a6ce630dc5b76550f6a602bddb44da8ff8e2a31d105bceL178-R203): Added a check for the availability of the jq tool and integrated it into the pretty_json function for sorting keys and formatting JSON strings. The function uses jq when available and falls back to the custom implementation otherwise.
I've read the …
=> feat(utils): use jq to format json if available

README.md, doc/extensions/copilotchat.md, doc/index.md, lua/mcphub/config.lua, lua/mcphub/extensions/copilotchat/functions.lua, lua/mcphub/extensions/copilotchat/init.lua, lua/mcphub/extensions/init.lua, lua/mcphub/native/init.lua, lua/mcphub/types.lua, lua/mcphub/utils/init.lua, lua/mcphub/utils/validation.lua
Adds native CopilotChat.nvim integration with function calling support, allowing MCP tools and resources to be used directly as CopilotChat functions.
- **Tool Integration**: Convert MCP tools to CopilotChat functions with proper schemas
- **Resource Integration**: Convert MCP resources to CopilotChat functions for easy access
- **Server Groups**: Functions organized by MCP server name for better organization
- **Safe Naming**: Conflict resolution for server names (handles cases like "mcp/everything" vs "mcp-everything")
- **Real-time Updates**: Automatic updates when MCP servers change
- **Configuration Options**: Flexible settings for function conversion and naming
```lua
require("mcphub").setup({
extensions = {
copilotchat = {
enabled = true,
convert_tools_to_functions = true,     -- …
```
=> feat: add CopilotChat extension support

doc/configuration.md
hello i'm new here, I found one typo. Maybe it's not wrong, please feel free
- [ x ] I've read the [contributing](https://github.com/ravitemer/mcphub.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [ x ] I've updated the README and/or relevant docs pages
- [ x ] I've run `make test` to ensure all tests pass
- [ x ] I've run `make format` to format the code
- [ x ] I've run `make docs` to update the vimdoc pages
=> typo: duplicate index 'global_env'

lua/mcphub/utils/renderer.lua
When a native server only defines prompts without tools, resources or resource templates, the server will not show
any capabilities in the mcphub UI:
with this little change, the prompts are also considered when deciding if capabilities are available:
=> fix(utils): add prompts for renderer filter condition

lua/mcphub/extensions/copilotchat/functions.lua
Add a safeguard in `create_function_name` to ensure generated function names do not exceed 64 characters. This prevents potential issues with overly long function names when registering MCP tools and resources as CopilotChat functions.
Fixes this error when function name is too long.
```
{"error":{"message":"Invalid 'tools[0].function.name': string too long. Expected a string with maximum length 64, but got a string with length 81 instead.","code":"string_above_max_length"}}
```
=> fix(copilotchat): limit function names to 64 characters
